Display signups to modules and details
ICTDTWDa3/Server pull request #41
Opened 2024-06-05 19:09 UTC by sisimaile

2024-06-06 13:57 UTC, tobokogo commented on Mvc/Controllers/ModuleChoiceController.cs
> +        public async Task<ActionResult> Detail(int moduleId)
@sisimaile SonarCloud geeft aan dat hier een ModulState.IsValid check moet gebeuren, denk wel goed om toe te voegen, zit ook wel in de andere endpoints volgens mij

2024-06-11 17:39 UTC, NielsGooz commented
Verwijder je database file(s) en migrations map

2024-06-11 17:40 UTC, NielsGooz requested changes

2024-06-11 17:40 UTC, NielsGooz commented on Mvc/Properties/launchSettings.json
> +      "distributionName": ""
Verwijder dit WSL profiel

2024-06-12 09:29 UTC, NielsGooz approved these changes

2024-06-12 11:21 UTC, merged